Antidote 1.6 (#50)
* Remove unnecessary bundles command
* Update man pages
* Bump version to 1.6.0
* Change error verbiage
* Formatting fixes
* Enhance list command
* Remove over-aggressive globbing
* Update man pages
* Feature #34 - support `purge --all`
* Change how MANPATH gets set

diff --git a/functions/antidote-purge b/functions/antidote-purge
--- a/functions/antidote-purge
+++ b/functions/antidote-purge
@@ -1,37 +1,80 @@
-#!/usr/bin/env zsh
-
 ### Remove a cloned bundle.
 ###
 ### usage: antidote purge [-h|--help] <bundle>
-
+###        antidote purge [-a|--all]
 emulate -L zsh
 setopt local_options extended_glob
 
-local o_help
-zparseopts -D -M -- h=o_help -help=h || return 1
+local o_help o_all
+zparseopts -D -M -- \
+  h=o_help -help=h  \
+  a=o_all  -all=a   ||
+  return 1
 
 if (( $#o_help )); then
   antidote-help purge
   return
 fi
 
-if [[ $# -eq 0 ]]; then
+if [[ $# -eq 0 ]] && ! (( $#o_all )); then
   echo >&2 "antidote: error: required argument 'bundle' not provided, try --help"
   return 1
 fi
 
-local bundle=$1
-local bundledir=$(_antidote_bundledir $bundle)
-if [[ ! -d $bundledir ]]; then
-  echo >&2 "antidote: error: $bundle does not exist at the expected location: $bundledir"
-  return 1
+local antidote_dir="$(antidote-home)"
+local bundlefile
+zstyle -s ':antidote:bundle' file 'bundlefile' ||
+  bundlefile=${ZDOTDIR:-~}/.zsh_plugins.txt
+
+if (( $#o_all )); then
+  if [[ ! -d $antidote_dir ]]; then
+    echo >&2 "antidote: error: Cannot find '$antidote_dir'."
+    return 1
+  fi
+
+  # last chance to save the user from themselves
+  local REPLY
+  zstyle -s ':antidote:purge:all' answer 'REPLY' || {
+    read -q "REPLY?You are about to permanently remove '$antidote_dir' and all its contents!"$'\n'"Are you sure [Y/n]? "
+    echo
+  }
+  [[ ${REPLY:u} == "Y" ]] || return 1
+
+  # remove antidote home and bundle file
+  command rm -rf "$antidote_dir"
+  local dtstmp=$(date -u '+%Y%m%d_%H%M%S')
+  if [[ -f "$bundlefile" ]]; then
+    mv -f "$bundlefile" "${bundlefile:r}.${dtstmp}.bak"
+    echo "# TODO: Add antidote bundles to this file..." >| "$bundlefile"
+    echo "'$bundlefile' backed up to '${bundlefile:t:r}.${dtstmp}.bak'"
+  fi
+  echo "Antidote purge complete. Be sure to start a new Zsh session."
+
+else
+  local bundle=$1
+  # make sure the user isn't trying to do something out-of-bounds
+  if [[ -e "$bundle" ]]; then
+    echo >&2 "antidote: error: '$bundle' is not a repo and cannot be removed by antidote."
+    return 2
+  fi
+
+  local bundledir=$(__antidote_bundledir $bundle)
+  if [[ ! -d "$bundledir" ]]; then
+    echo >&2 "antidote: error: $bundle does not exist at the expected location: $bundledir"
+    return 1
+  fi
+
+  # remove
+  command rm -rf "$bundledir"
+  echo "Removed '$bundle'."
+
+  # attempt to comment out the bundle from .zsh_plugins.txt
+  if [[ -f "$bundlefile" ]]; then
+    local tmpfile="${bundlefile}.antidote.tmp"
+    awk -v pat="$bundle" '$0~"^[[:blank:]]*"pat{print "# " $0;next}{print}' <$bundlefile >|$tmpfile
+    mv -f "$tmpfile" "$bundlefile" || rm -f "$tmpfile"
+    echo "Bundle '$bundle' was commented out in '$bundlefile'."
+  fi
 fi
 
-echo "Removing $bundle..."
-command rm -rf "$bundledir"
-
-local bundlefile
-zstyle -s ':antidote:bundle' file 'bundlefile' || \
-  bundlefile=${ZDOTDIR:-~}/.zsh_plugins.txt
-echo "removed!"
-echo "You may also need to remove $bundle from '$bundlefile'."
+# vim: ft=zsh
