1.7.5 (#103)
* Update man pages

* Use shebang over vim modeline

- Works with more editors
- We already use an .editorconfig

* Style: add function wrappers

* Do autoloads first

* Add another safety check for `purge --all`

* Support `.mockgit` dirs for testing

- Using `.git` dirs in fakes is problematic

* install: Support more annotations

* Refactor antidote-main

* Fail when sourced by bash accidentally

* Fix test output

* Add testdata

* Style: add test function wrappers

* tests: Change fakezdotdir

* tests: Rename fake ohmyzsh to ohmy

* tests: Rename fakezdotdir to zdotdir

* tests: Cleanup

- Cleanup fake zdotdir
- Move .zsh_plugins_expected.zsh to testdata folder
- Remove unneeded zshrc.d dir
- Remove unneeded tool

* tests: Rename bar/baz and baz/qux fakes

diff --git a/functions/antidote-list b/functions/antidote-list
--- a/functions/antidote-list
+++ b/functions/antidote-list
@@ -1,41 +1,45 @@
+#!/bin/zsh
+
 ### List cloned bundles.
 #
 # usage: antidote list [-h|--help]
 #
-emulate -L zsh; setopt $_adote_funcopts
+function antidote-list {
+  emulate -L zsh; setopt $_adote_funcopts
 
-local o_help o_short o_dirs
-zparseopts $_adote_zparopt_flags -- \
-  h=o_help  -help=h  \
-  s=o_short -short=s \
-  d=o_dirs  -dirs=d  ||
-  return 1
+  local o_help o_short o_dirs
+  zparseopts $_adote_zparopt_flags -- \
+    h=o_help  -help=h  \
+    s=o_short -short=s \
+    d=o_dirs  -dirs=d  ||
+    return 1
 
-if (( $#o_help )); then
-  antidote-help list
-  return
-fi
-
-if [[ $# -ne 0 ]]; then
-  echo >&2 "antidote: error: unexpected $1, try --help"
-  return 1
-fi
-
-local bundledir
-local output=()
-local bundles=($(antidote-home)/**/.git/..(/N))
-for bundledir in $bundles; do
-  local url=$(git -C "${bundledir:A}" config remote.origin.url)
-  if (( $#o_dirs )); then
-    output+=(${bundledir:A})
-  elif (( $#o_short )); then
-    url=${url%.git}
-    url=${url#https://github.com/}
-    output+=($url)
-  else
-    output+=("$(printf '%-64s %s\n' $url ${bundledir:A})")
+  if (( $#o_help )); then
+    antidote-help list
+    return
   fi
-done
-printf '%s\n' "${(o)output[@]}"
 
-# vim: ft=zsh sw=2 ts=2 et
+  if [[ $# -ne 0 ]]; then
+    echo >&2 "antidote: error: unexpected $1, try --help"
+    return 1
+  fi
+
+  local bundledir
+  local output=()
+  local bundles=($(antidote-home)/**/.{mock,}git/..(/N))
+
+  for bundledir in $bundles; do
+    local url=$(git -C "${bundledir:A}" config remote.origin.url)
+    if (( $#o_dirs )); then
+      output+=(${bundledir:A})
+    elif (( $#o_short )); then
+      url=${url%.git}
+      url=${url#https://github.com/}
+      output+=($url)
+    else
+      output+=("$(printf '%-64s %s\n' $url ${bundledir:A})")
+    fi
+  done
+  printf '%s\n' "${(o)output[@]}"
+}
+antidote-list "$@"
diff --git a/functions/antidote-path b/functions/antidote-path
--- a/functions/antidote-path
+++ b/functions/antidote-path
@@ -1,29 +1,32 @@
+#!/bin/zsh
+
 ### Print the path of a cloned bundle.
 #
 # usage: antidote path [-h|--help] <bundle>
 #
-emulate -L zsh; setopt $_adote_funcopts
+function antidote-path {
+  emulate -L zsh; setopt $_adote_funcopts
 
-local o_help
-zparseopts $_adote_zparopt_flags -- h=o_help -help=h || return 1
+  local o_help
+  zparseopts $_adote_zparopt_flags -- h=o_help -help=h || return 1
 
-if (( $#o_help )); then
-  antidote-help path
-  return
-fi
+  if (( $#o_help )); then
+    antidote-help path
+    return
+  fi
 
-if [[ $# -eq 0 ]]; then
-  echo >&2 "antidote: error: required argument 'bundle' not provided, try --help"
-  return 1
-fi
+  if [[ $# -eq 0 ]]; then
+    echo >&2 "antidote: error: required argument 'bundle' not provided, try --help"
+    return 1
+  fi
 
-local bundle="$1"
-local bundledir=$(__antidote_bundledir $bundle)
-if [[ ! -d $bundledir ]]; then
-  echo >&2 "antidote: error: $bundle does not exist in cloned paths"
-  return 1
-else
-  echo "$bundledir"
-fi
-
-# vim: ft=zsh sw=2 ts=2 et
+  local bundle="$1"
+  local bundledir=$(__antidote_bundledir $bundle)
+  if [[ ! -d $bundledir ]]; then
+    echo >&2 "antidote: error: $bundle does not exist in cloned paths"
+    return 1
+  else
+    echo "$bundledir"
+  fi
+}
+antidote-path "$@"
diff --git a/tests/functions/mockgit b/tests/functions/mockgit
--- a/tests/functions/mockgit
+++ b/tests/functions/mockgit
@@ -1,51 +1,58 @@
-# handle these commands:
-# - `git -C "$dir" config remote.origin.url`
-# - `git -C "$dir" pull --quiet --ff --rebase --autostash`
-# - `git -C "$dir" rev-parse --short HEAD`
-# - `git clone --quiet --depth 1 --recurse-submodules --shallow-submodules --branch branch $url $dir`
+#!/bin/zsh
+function mockgit {
+  # handle these commands:
+  # - `git -C "$dir" config remote.origin.url`
+  # - `git -C "$dir" pull --quiet --ff --rebase --autostash`
+  # - `git -C "$dir" rev-parse --short HEAD`
+  # - `git clone --quiet --depth 1 --recurse-submodules --shallow-submodules --branch branch $url $dir`
+  # - `git --version`
+  emulate -L zsh; setopt local_options extended_glob
+  0=${(%):-%x}
 
-local args=("$@[@]")
-local o_path o_quiet o_ff o_rebase o_autostash o_short
-local o_depth o_recurse_submodules o_shallow_submodules o_branch
-zparseopts -D -E --      \
-  C:=o_path              \
-  -short=o_short         \
-  -quiet=o_quiet         \
-  -ff=o_ff               \
-  -rebase=o_rebase       \
-  -autostash=o_autostash \
-  -recurse-submodules=o_recurse_submodules \
-  -shallow-submodules=o_shallow_submodules \
-  -depth:=o_depth                          \
-  -branch:=o_branch                        ||
-  return 1
+  local args=("$@[@]")
+  local o_path o_quiet o_ff o_rebase o_autostash o_short
+  local o_depth o_recurse_submodules o_shallow_submodules o_branch
+  zparseopts -D -E --      \
+    C:=o_path              \
+    -short=o_short         \
+    -quiet=o_quiet         \
+    -ff=o_ff               \
+    -rebase=o_rebase       \
+    -autostash=o_autostash \
+    -recurse-submodules=o_recurse_submodules \
+    -shallow-submodules=o_shallow_submodules \
+    -depth:=o_depth                          \
+    -branch:=o_branch                        ||
+    return 1
 
-if [[ "$1" = "clone" ]]; then
-  local giturl="$2"
-  local bundledir="$3"
-  local src="$FAKEZDOTDIR/antidote_home/${bundledir:t}"
-  if [[ -d $src ]]; then
-    cp -r $src ${bundledir:h}
-  elif ! (( $#o_quiet )); then
-    echo "FAKEGIT: Cloning into '${url:t}'..."
-    echo "FAKEGIT: Repository not found."
-    echo "FAKEGIT: repository '$url' not found"
+  if [[ "$@" = "--version" ]]; then
+    echo "0.0.0"
+  elif [[ "$1" = "clone" ]]; then
+    local giturl="$2"
+    local bundledir="$3"
+    local src="$FAKEZDOTDIR/antidote_home/${bundledir:t}"
+    if [[ -d $src ]]; then
+      cp -r $src ${bundledir:h}
+    elif ! (( $#o_quiet )); then
+      echo "FAKEGIT: Cloning into '${url:t}'..."
+      echo "FAKEGIT: Repository not found."
+      echo "FAKEGIT: repository '$url' not found"
+    fi
+  elif [[ "$@" = "config remote.origin.url" ]]; then
+    # un-sanitize dir into URL
+    local url=$o_path[-1]
+    url=${url:t}
+    url=${url:gs/-AT-/\@}
+    url=${url:gs/-COLON-/\:}
+    url=${url:gs/-SLASH-/\/}
+    echo "$url"
+  elif [[ "$@" = "pull" ]]; then
+    (( $#o_quiet )) || echo "FAKEGIT: Already up to date."
+  elif [[ "$@" = "rev-parse HEAD" ]]; then
+    echo "a123456"
+  else
+    echo >&2 "mocking not implemented for git command: git $@"
+    return 1
   fi
-elif [[ "$@" = "config remote.origin.url" ]]; then
-  # un-sanitize dir into URL
-  local url=$o_path[-1]
-  url=${url:t}
-  url=${url:gs/-AT-/\@}
-  url=${url:gs/-COLON-/\:}
-  url=${url:gs/-SLASH-/\/}
-  echo "$url"
-elif [[ "$@" = "pull" ]]; then
-  (( $#o_quiet )) || echo "FAKEGIT: Already up to date."
-elif [[ "$@" = "rev-parse HEAD" ]]; then
-  echo "a123456"
-else
-  echo >&2 "mocking not implemented for git command: git $@"
-  return 1
-fi
-
-# vim: ft=zsh sw=2 ts=2 et
+}
+mockgit "$@"
