Fix #8: add remaining help docs

diff --git a/functions/antidote-help b/functions/antidote-help
--- a/functions/antidote-help
+++ b/functions/antidote-help
@@ -1,57 +1,15 @@
 #!/usr/bin/env zsh
-local help=()
+0=${(%):-%x}
+local help_dir="${0:a:h:h}/help"
+antidote_help="$help_dir/antidote.txt"
+if [[ -z "$1" ]]; then
+  cat "$antidote_help"
+  return
+fi
 
-case "$1" in
-  '')
-    help=(
-      'usage: antidote [<flags>] <command> [<args> ...]'
-      ''
-      'The fast and native Zsh plugin manager'
-      ''
-      'Flags:'
-      '-h, --help           Show context-sensitive help.'
-      '-v, --version        Show application version.'
-      ''
-      'Commands:'
-      '  help [<command>...]'
-      '    show help'
-      ''
-      '  bundle [<bundles>...]'
-      '    downloads a bundle and prints its source line'
-      ''
-      '  update'
-      '    updates all previously bundled bundles'
-      ''
-      '  home'
-      '    prints where antidote is cloning the bundles'
-      ''
-      '  purge <bundle>'
-      '    purges a bundle from your computer'
-      ''
-      '  list'
-      '    lists all currently installed bundles'
-      ''
-      '  path <bundle>'
-      '    prints the path of a currently cloned bundle'
-    )
-    ;;
-  bundle)
-    help=(
-      'usage: antidote bundle [<bundles>...]'
-      ''
-      'downloads a bundle and prints its source line'
-      ''
-      'Flags:'
-      '  -h, --help           Show context-sensitive help.'
-      '  -v, --version        Show application version.'
-      'Args:'
-      '  [<bundles>]  bundle list'
-    )
-    ;;
-  *)
-    echo "No extended help available for command: $@"
-    return 1
-    ;;
-esac
-
-printf "%s\n" "${help[@]}"
+local help_txt="${help_dir}/antidote-${1}.txt"
+if [[ ! -f "$help_txt" ]]; then
+  echo >&2 "antidote: error: expected valid command but got '$@'"
+  return 1
+fi
+cat "$help_txt"
