Add tests for script command

diff --git a/functions/antidote-script b/functions/antidote-script
--- a/functions/antidote-script
+++ b/functions/antidote-script
@@ -6,7 +6,7 @@
 # <bundle> : A bundle can be a directory, a zsh script, or a git repo
 
 emulate -L zsh
-setopt local_options extended_glob
+setopt local_options extended_glob rematch_pcre
 
 local o_help o_kind o_path
 zparseopts $_adote_zparopt_flags -- \
@@ -15,7 +15,16 @@ zparseopts $_adote_zparopt_flags -- \
   p:=o_path -path:=p ||
   return 1
 
+# strip '=' or ':' from arg values
+local re='^[=:]?(.+)$'
+[[ $o_kind[-1] =~ $re ]] && o_kind[-1]=$match
+[[ $o_path[-1] =~ $re ]] && o_path[-1]=$match
+
 [[ "$o_kind[-1]" != "clone" ]] || return
+local supported_kind_vals=(zsh path fpath defer)
+if (( $#o_kind )) && ! (( $supported_kind_vals[(Ie)$o_kind[-1]] )); then
+  echo >&2 "antidote: error: unexpected kind value: '$o_kind[-1]'" && return 1
+fi
 
 local bundle=$1
 if [[ -z "$bundle" ]]; then
