v1.8.0 (#108)
* tests: Rename tests

* tests: Remove legacy tests and funcs

* tests: Add bash and main cmd tests

* help: Add comments and use localopts

* antidote: Better shellname check

* tests: Fix broken test

* helpers: Rename __antidote_bundle_dir

* helpers: Remove awk files

* tests: Test man pages

* main: Move setup to its own func

- Move private funcs
- Prep for fixing #106

* update: Fix #106

* main: Refactor

- Add version func
- Remove legacy setup method

* bundle: Refactor to use simple awk parsers

* script: Fix clone verbiage

* script: Cleanup

* tests: Refactor and add tests

* Bump version to 1.8.0

diff --git a/tests/functions/mockgit b/tests/functions/mockgit
--- a/tests/functions/mockgit
+++ b/tests/functions/mockgit
@@ -31,13 +31,13 @@ function mockgit {
   elif [[ "$1" = "clone" ]]; then
     local giturl="$2"
     local bundledir="$3"
-    local src="$FAKEZDOTDIR/antidote_home/${bundledir:t}"
+    local src="$ANTIDOTE_HOME/${bundledir:t}"
     if [[ -d $src ]]; then
       cp -r $src ${bundledir:h}
     elif ! (( $#o_quiet )); then
-      echo "FAKEGIT: Cloning into '${url:t}'..."
-      echo "FAKEGIT: Repository not found."
-      echo "FAKEGIT: repository '$url' not found"
+      echo "MOCKGIT: Cloning into '${url:t}'..."
+      echo "MOCKGIT: Repository not found."
+      echo "MOCKGIT: repository '$url' not found"
     fi
   elif [[ "$@" = "config remote.origin.url" ]]; then
     # un-sanitize dir into URL
@@ -48,7 +48,7 @@ function mockgit {
     url=${url:gs/-SLASH-/\/}
     echo "$url"
   elif [[ "$@" = "pull" ]]; then
-    (( $#o_quiet )) || echo "FAKEGIT: Already up to date."
+    (( $#o_quiet )) || echo "MOCKGIT: Already up to date."
   elif [[ "$@" = "rev-parse HEAD" ]]; then
     #echo "a123456"
     echo ""
